### ISSUE TITLE
issue with prismarine shaders

### ISSUE THREAD

**Issue by TheNukeLore** [BalintCsala/ShaderOptionsManager#1]
if you try to open prismarine shaders with this, nothing happens. it just tries to load but fails but still creates the tmp folder

**Comment by BalintCsala** [comment]
It loads the latest version of prismarine shaders for me. Would you mind opening a command line where the jar file is, running it with `java -jar ShaderOptionsManager.jar` and pasting the result here?

**Comment by TheNukeLore** [comment]
Ya never mind about that, I just didn’t have the shader set up correctly so it could read it.
